import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import Header from '@/components/header/Header'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div id={styles.bgHome}>
        <hgroup id={styles.titulosHome}>
          <h1 id={styles.tituloUm}>Instituto</h1>
          <h1 id={styles.tituloDois}>Corporali.</h1>
          <p id={styles.tituloTres}>Somos o instituido Corporali. Aqui você alcança os seus objetivos de uma forma segura e proficional</p>
        </hgroup>
        <div id={styles.boxSaberMais}>
          <a id={styles.saberMais} href="">Saber Mais!</a>
        </div>
      </div>
    </>
  )
}
