import Head from 'next/head';
import styles from '@/styles/index.module.scss';
import Header from '@/components/header/Header';
import Image from 'next/image';

import { robotoCondensed } from '@/fonts/fonts';

import LinhaHorizontalLonga from '@/components/linhaHorizontalLonga/LinhaHorizontalLonga.jsx';

export default function Home() {
  return (
    <div className={robotoCondensed.className}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div id={styles.bgHome}>
        <hgroup>
          <h1 id={styles.tituloUm}>Instituto</h1>
          <h1 id={styles.tituloDois}>Corporali.</h1>
          <p id={styles.tituloTres}>Somos o instituido Corporali. Aqui você alcança os seus objetivos de uma forma segura e proficional</p>
        </hgroup>
        <div id={styles.boxSaberMais}>
          <a id={styles.saberMais} href="">Saber Mais!</a>
        </div>
      </div>

      <LinhaHorizontalLonga/>
      
      <div id={styles.clinica}>
        <div id={styles.fotoClinica}> 
          <div id={styles.conteudoClinica}>
            <div id={styles.sloganClinica}>
              <h2 id={styles.tituloSloganClinica}>Corporali</h2>
              <p id={styles.descricaoSloganClinica}>O nosso maior prazer é atender voce e te ver bem.</p>
            </div>
            <div id={styles.sobreaClinica}>
              <h2 id={styles.tituloSobreaClinica}>Sobre a <strong id={styles.tituloClinicaVerde}>Cliníca</strong></h2>
              <p className={styles.descricaoClinica}>Idealizado para oferecer o que há de melhor em procedimentos cirúrgicos, com profissionais altamente qualificados e as melhores tecnologias disponíveis, o Instituto Corporali é focado na necessidade e expectativa dos nossos pacientes, buscando compreender as suas necessidades e oferecendo caminhos para alcançar o melhor resultado.</p>
              <p className={styles.descricaoClinica}>A nossa estrutura conta com um espaço amplo e em uma excelente localização, o que são detalhes pensados no conforto, segurança e praticidade dos nossos pacientes.</p>
              <p className={styles.descricaoClinica}>A nossa estrutura conta com um espaço amplo e em uma excelente localização, o que são detalhes pensados no conforto, segurança e praticidade dos nossos pacientes.</p>
              <div id={styles.boxLinhaBranca}>
                <div id={styles.linhaBranca}></div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <LinhaHorizontalLonga/>

      <div id={styles.procedimentos}></div>

      <div id={styles.procedimentos}></div>

      <div id={styles.marcelo}></div>

      <div id={styles.duvidas}></div>

      <div id={styles.contato}></div>
    </div>
  )
}
